#!/usr/bin/env bash
# Uninstall smartctx: the Python package (pipx or pip) and, on request,
# the per-profile and per-repo configuration it wrote.
set -euo pipefail

warn() { printf "smartctx: %s\n" "$*" >&2; }

confirm() {
    local prompt="$1"
    local answer
    read -r -p "$prompt [y/N] " answer
    [[ "$answer" =~ ^[yY]([eE][sS])?$ ]]
}

uninstall_pkg() {
    if command -v pipx >/dev/null 2>&1 \
        && pipx list --short 2>/dev/null | grep -Eq '^[[:space:]]*smartctx([[:space:]]|$)'; then
        warn "found smartctx installed via pipx — running: pipx uninstall smartctx"
        if ! pipx uninstall smartctx; then
            warn "pipx uninstall failed; remove it by hand, then re-run for config cleanup"
        fi
        return
    fi
    if command -v smartctx >/dev/null 2>&1; then
        warn "smartctx on PATH but not via pipx — trying pip instead"
        if ! python3 -m pip uninstall -y smartctx; then
            warn "automatic uninstall failed; do it by hand from the environment that provides"
            warn "  $(command -v smartctx)"
        fi
        return
    fi
    warn "no smartctx install found (pipx or pip); skipping package removal"
}

cleanup_user_config() {
    local config_dir
    if [[ -n "${CLAUDE_CONFIG_DIR:-}" ]]; then
        config_dir="${CLAUDE_CONFIG_DIR/#\~/$HOME}"
    else
        config_dir="$HOME/.claude"
    fi
    local user_cfg="$config_dir/smartctx"

    if [[ -d "$user_cfg" ]] && confirm "remove $user_cfg (config.toml, rules.toml)? "; then
        rm -rf "$user_cfg"
        warn "removed $user_cfg"
    fi
}

# Only dirs that carry a smartctx-authored artifact are ours to delete; this guards
# against nuking an unrelated directory that merely happens to be named .smartctx.
is_smartctx_dir() {
    local d="$1"
    [[ -f "$d/goal" || -f "$d/config.toml" || -f "$d/rules.toml" ]] && return 0
    [[ -f "$d/.gitignore" ]] && grep -q "generated by smartctx" "$d/.gitignore" && return 0
    return 1
}

# smartctx writes a .smartctx/ into every repo it launches in; find and remove them
# filesystem-wide. Scans $HOME by default (fast, avoids system/mounted volumes and the
# permission noise of a full-tree walk); the prompt lets you widen the root, e.g. to /.
cleanup_repo_configs() {
    local default_root="$HOME" root
    read -r -p "scan for per-repo .smartctx/ dirs under [$default_root] (blank to accept, or type a path): " root
    root="${root:-$default_root}"
    root="${root/#\~/$HOME}"
    if [[ ! -d "$root" ]]; then
        warn "scan root $root does not exist; skipping per-repo cleanup"
        return
    fi

    warn "scanning $root for .smartctx/ directories …"
    local -a found=()
    while IFS= read -r -d '' d; do
        is_smartctx_dir "$d" && found+=("$d")
    done < <(find "$root" -type d -name .smartctx -print0 2>/dev/null)

    if [[ ${#found[@]} -eq 0 ]]; then
        warn "no per-repo .smartctx/ directories found under $root"
        return
    fi

    warn "found ${#found[@]} .smartctx/ director$([[ ${#found[@]} -eq 1 ]] && echo y || echo ies):"
    printf '  %s\n' "${found[@]}" >&2
    if confirm "remove all ${#found[@]} listed .smartctx/ director$([[ ${#found[@]} -eq 1 ]] && echo y || echo ies)? "; then
        for d in "${found[@]}"; do
            rm -rf "$d" && warn "removed $d"
        done
    fi
}

warn "uninstalling smartctx"
uninstall_pkg
cleanup_user_config
cleanup_repo_configs
cat >&2 <<'EOF'
smartctx: done. Remaining by hand:
  - remove any aliases you added to your shell rc (e.g. alias claude-work="... smartctx")
  - optionally drop the now-stale ~/.claude-work / ~/.claude-perso profile dirs
EOF
