#!/usr/bin/env bash
# Uninstall claude-loadout: the Python package (pipx or pip) and, on request,
# the per-profile and per-repo configuration it wrote.
set -euo pipefail

warn() { printf "loadout: %s\n" "$*" >&2; }

confirm() {
    local prompt="$1"
    local answer
    read -r -p "$prompt [y/N] " answer
    [[ "$answer" =~ ^[yY]([eE][sS])?$ ]]
}

uninstall_pkg() {
    if command -v pipx >/dev/null 2>&1 \
        && pipx list --short 2>/dev/null | grep -Eq '^[[:space:]]*ccloadout([[:space:]]|$)'; then
        warn "found loadout installed via pipx — running: pipx uninstall ccloadout"
        if ! pipx uninstall ccloadout; then
            warn "pipx uninstall failed; remove it by hand, then re-run for config cleanup"
        fi
        return
    fi
    if command -v claude-loadout >/dev/null 2>&1; then
        warn "loadout on PATH but not via pipx — trying pip instead"
        if ! python3 -m pip uninstall -y ccloadout; then
            warn "automatic uninstall failed; do it by hand from the environment that provides"
            warn "  $(command -v claude-loadout)"
        fi
        return
    fi
    warn "no loadout install found (pipx or pip); skipping package removal"
}

cleanup_user_config() {
    local config_dir
    if [[ -n "${CLAUDE_CONFIG_DIR:-}" ]]; then
        config_dir="${CLAUDE_CONFIG_DIR/#\~/$HOME}"
    else
        config_dir="$HOME/.claude"
    fi
    local user_cfg="$config_dir/loadout"

    if [[ -d "$user_cfg" ]] && confirm "remove $user_cfg (config.toml, rules.toml)? "; then
        rm -rf "$user_cfg"
        warn "removed $user_cfg"
    fi
}

# Only dirs that carry a loadout-authored artifact are ours to delete; this guards
# against nuking an unrelated directory that merely happens to be named .loadout.
is_loadout_dir() {
    local d="$1"
    [[ -f "$d/goal" || -f "$d/config.toml" || -f "$d/rules.toml" ]] && return 0
    [[ -f "$d/.gitignore" ]] && grep -q "generated by loadout" "$d/.gitignore" && return 0
    return 1
}

# loadout writes a .loadout/ into every repo it launches in; find and remove them
# filesystem-wide. Scans $HOME by default (fast, avoids system/mounted volumes and the
# permission noise of a full-tree walk); the prompt lets you widen the root, e.g. to /.
cleanup_repo_configs() {
    local default_root="$HOME" root
    read -r -p "scan for per-repo .loadout/ dirs under [$default_root] (blank to accept, or type a path): " root
    root="${root:-$default_root}"
    root="${root/#\~/$HOME}"
    if [[ ! -d "$root" ]]; then
        warn "scan root $root does not exist; skipping per-repo cleanup"
        return
    fi

    warn "scanning $root for .loadout/ directories …"
    local -a found=()
    while IFS= read -r -d '' d; do
        is_loadout_dir "$d" && found+=("$d")
    done < <(find "$root" -type d -name .loadout -print0 2>/dev/null)

    if [[ ${#found[@]} -eq 0 ]]; then
        warn "no per-repo .loadout/ directories found under $root"
        return
    fi

    warn "found ${#found[@]} .loadout/ director$([[ ${#found[@]} -eq 1 ]] && echo y || echo ies):"
    printf '  %s\n' "${found[@]}" >&2
    if confirm "remove all ${#found[@]} listed .loadout/ director$([[ ${#found[@]} -eq 1 ]] && echo y || echo ies)? "; then
        for d in "${found[@]}"; do
            rm -rf "$d" && warn "removed $d"
        done
    fi
}

warn "uninstalling loadout"
uninstall_pkg
cleanup_user_config
cleanup_repo_configs
cat >&2 <<'EOF'
loadout: done. Remaining by hand:
  - remove any aliases you added to your shell rc (e.g. alias claude-work="... claude-loadout")
  - optionally drop the now-stale ~/.claude-work / ~/.claude-perso profile dirs
EOF
