from __future__ import annotations
import hashlib, json, re, tomllib
from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class GoalResult:
    goal: str
    confidence: float
    source: str

_DESC_CAP = 200                                    # keep the blurb short so it can't swamp the embedding
_LINKY = re.compile(r'!?\[([^\]]*)\]\([^)]*\)')    # [text](url) / ![alt](src) -> text
_NOISE_PREFIX = ("!", "[!", "<", ">", "|", "```", "~~~")   # image/badge, html, quote, table, fence
_BULLET = re.compile(r'^([-*+]\s|\d+\.\s)')        # list item — drop, but keep **bold** taglines
_HR = re.compile(r'^([-*=_]){3,}\s*$')             # horizontal rule

_MAX_META = 1_000_000                              # don't parse a multi-MB generated config

def _small_text(path: Path) -> str | None:
    try:
        if path.stat().st_size > _MAX_META:
            return None
        return path.read_text(errors="ignore")
    except OSError:
        return None

def _metadata_description(cwd: Path) -> str | None:
    raw = _small_text(cwd / "pyproject.toml")
    if raw is not None:
        try:
            d = tomllib.loads(raw).get("project", {}).get("description")
            if isinstance(d, str) and d.strip():
                return d.strip()
        except tomllib.TOMLDecodeError:
            pass
    raw = _small_text(cwd / "package.json")
    if raw is not None:
        try:
            d = json.loads(raw).get("description")
            if isinstance(d, str) and d.strip():
                return d.strip()
        except json.JSONDecodeError:
            pass
    return None

def _clean(line: str) -> str:
    line = _LINKY.sub(r"\1", line).replace("`", "").replace("*", "")   # drop emphasis markers
    return line.lstrip("#>= ").strip()

def _find_readme(cwd: Path) -> Path | None:
    try:                                           # prefer README.md, then shortest README* name
        readmes = sorted((p for p in cwd.iterdir()
                          if p.is_file() and p.name.lower().startswith("readme")),
                         key=lambda p: (p.suffix.lower() != ".md", len(p.name)))
    except OSError:
        return None
    return readmes[0] if readmes else None

def _readme_blurb(cwd: Path) -> str | None:
    readme = _find_readme(cwd)
    if readme is None:
        return None
    try:                                           # read only the head; READMEs are arbitrary user files
        with readme.open("r", errors="ignore") as fh:
            text = fh.read(8192)
    except OSError:
        return None
    title, para = None, []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            if para:                               # blank line ends the first real paragraph
                break
            continue
        heading = line.startswith("#")
        noise = not heading and (line.startswith(_NOISE_PREFIX)
                                 or bool(_BULLET.match(line)) or bool(_HR.match(line)))
        if noise:                                  # badges, tables, quotes, rules, fences, bullets
            if para:
                break
            continue
        cleaned = _clean(line)
        if not cleaned:
            continue
        if title is None:                          # first heading or first plain line = the name
            title = cleaned
            continue
        if heading:                                # a second heading ends the intro
            break
        para.append(cleaned)
    if title is None:
        return None
    blurb = title if not para else f"{title} — {' '.join(para)}"
    return re.sub(r"\s+", " ", blurb).strip()

def _read_description(cwd: Path) -> str | None:
    # Curated metadata one-liner wins; else the README's title + first paragraph.
    desc = _metadata_description(cwd) or _readme_blurb(cwd)
    return desc[:_DESC_CAP].rstrip() if desc else None

_CACHE = lambda cwd: cwd / ".loadout" / "goal"
# The goal file stays a single line (older releases read it whole); what it was derived from and
# who chose it live beside it: `inputs=<sha1> origin=inferred|user`.
_META = lambda cwd: cwd / ".loadout" / "goal.meta"
_MIN_CONFIDENCE = 0.15                             # below this a launch asks; never replace a goal with it

# Machine-generated state that must never be committed. Authored files
# (config.toml, rules.toml) are intentionally left out so a team can share them.
_GITIGNORE = "# generated by loadout — machine state, do not commit\ngoal\ngoal.meta\n"

def _inputs_digest(cwd: Path) -> str:
    """Fingerprint of the cheap inputs a goal is inferred from.

    Directory name, the metadata description, the head of the README that would be read, and
    which marker files exist. The recursive `*.tsx` probe is left out on purpose: it can walk a
    whole dependency tree, and a launch pays for this on every start.
    """
    readme, head = _find_readme(cwd), b""
    if readme is not None:
        try:
            with readme.open("rb") as fh:
                head = fh.read(8192)
        except OSError:
            pass
    parts = [cwd.name, _metadata_description(cwd) or "",
             str((cwd / "pyproject.toml").exists()), str((cwd / "package.json").exists())]
    return hashlib.sha1("\0".join(parts).encode() + b"\0" + head).hexdigest()

def _read_meta(cwd: Path) -> dict[str, str]:
    try:
        text = _META(cwd).read_text()
    except OSError:
        return {}
    return dict(field.split("=", 1) for field in text.split() if "=" in field)

def write_goal_cache(cwd: Path, goal: str, origin: str | None = None) -> None:
    """Persist the goal, plus the digest of its inputs and whether it was inferred or chosen.

    Without an explicit origin, a goal equal to what inference gives today counts as inferred and
    anything else as the user's own; a user goal is never refreshed behind their back.
    """
    d = cwd / ".loadout"; d.mkdir(exist_ok=True)
    ignore = d / ".gitignore"
    if not ignore.exists():                            # self-ignore so the cache never lands in git
        ignore.write_text(_GITIGNORE)
    else:                                              # ours, from before the sidecar existed: extend it
        lines = ignore.read_text().splitlines()        # (a user-authored ignore is never touched)
        if lines and lines[0] == _GITIGNORE.splitlines()[0] and "goal.meta" not in lines:
            ignore.write_text("\n".join([*lines, "goal.meta"]) + "\n")
    goal = goal.strip()
    (d / "goal").write_text(goal + "\n")
    if origin is None:
        origin = "inferred" if goal == _infer(cwd).goal else "user"
    _META(cwd).write_text(f"inputs={_inputs_digest(cwd)} origin={origin}\n")

def detect_goal(cwd: Path, use_cache: bool = True, persist: bool = True) -> GoalResult:
    """The session goal: the cached one while it is still current, otherwise a fresh inference.

    A cached goal is reused when the user chose it or its inputs are unchanged. When the inputs
    changed (or a cache predates the sidecar), inference runs again; a confident new goal replaces
    the cached one (source "refreshed", written back unless `persist` is False, as for --explain),
    a weak one leaves it alone. `update` passes use_cache=False to always re-infer.
    """
    cache = _CACHE(cwd)
    if use_cache and cache.is_file():
        txt = cache.read_text().strip()
        if txt:
            meta = _read_meta(cwd)
            if meta.get("origin") == "user" or meta.get("inputs") == _inputs_digest(cwd):
                return GoalResult(goal=txt, confidence=1.0, source="cache")
            fresh = _infer(cwd)
            if fresh.confidence < _MIN_CONFIDENCE or fresh.goal == txt:
                if persist:                         # remember the inputs, so this isn't redone each launch
                    write_goal_cache(cwd, txt, origin=meta.get("origin") or
                                     ("inferred" if fresh.goal == txt else "user"))
                return GoalResult(goal=txt, confidence=1.0, source="cache")
            if persist:
                write_goal_cache(cwd, fresh.goal, origin="inferred")
            return GoalResult(goal=fresh.goal, confidence=fresh.confidence, source="refreshed")
    return _infer(cwd)

def _infer(cwd: Path) -> GoalResult:
    tech: list[str] = []
    conf = 0.0
    if (cwd / "pyproject.toml").exists():
        tech.append("python project"); conf += 0.3
    if (cwd / "package.json").exists():
        tech.append("javascript project"); conf += 0.3
    if any(cwd.glob("*.tsx")) or any(cwd.glob("**/*.tsx")):
        tech.append("react frontend"); conf += 0.3
    desc = _read_description(cwd)
    if desc:                                       # a real purpose blurb leads; tech tags add keywords
        goal = f"{desc} · {', '.join(tech)}" if tech else desc
        return GoalResult(goal=goal, confidence=min(1.0, conf + 0.4), source="docs")
    if _find_readme(cwd) is not None:               # README present but yielded no blurb
        conf += 0.1
    if conf == 0.0:
        return GoalResult(goal=cwd.name, confidence=0.0, source="none")
    return GoalResult(goal=" ".join([cwd.name, *tech]), confidence=min(conf, 1.0), source="signals")
